---
galaxy_info:
  author: elnappo <elnappo@nerdpol.io>
  description: Install apt-cacher-ng
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  galaxy_tags:
  - packaging
  - apt

dependencies: []
